yarnPath: .yarn/releases/yarn-4.3.1.cjs
nmHoistingLimits: workspaces
nmMode: hardlinks-global
plugins:
  - path: plugins/tool-workspace/bundles/@yarnpkg/plugin-tool-workspace.js
toolWorkspace: "@appthrust/toolbox"
