name: pipeline
on:
  push:
    branches:
      - main
  pull_request: null
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          # Installation without cache took 20 seconds
          # Saving the cache took 2 minutes and 42 seconds
          # The reason was the network
          # Therefore, the cache has been disabled
          # https://github.com/appthrust/appthrust/actions/runs/8748865011/job/24009561052?pr=31
          cache: false
          auto-install: true
      - run: moon ci --color
      - uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: appthrust/moon-ci-retrospect@v0
        if: success() || failure()
